### ISSUE TITLE
Copy to Folder - Does not copy files

### ISSUE THREAD

**Issue by supertoothy** [doug-101/TreeTag#3] opened 2024-04-18 03:18 UTC
The Issue: After I have created a .trtg file, I Export to Treeline. Then I select the newly created .trln file and select Copy to Folder. I am asked to provide permissions, which I provide (each time), and then select the folder to be copied to. 

Later when I check the folder, the file has not been copied to the desired folder.

I am using Treetag Ver 0.7.2 on a phone running Android Ver 13.

----

Thank you for this lovely application. Treetag is such a novel idea, and scrolling down the tree to see my data grouped in different categories is great. I've also enjoyed Treeline for many years, my thanks for that as well.

**Comment by ME7DYCgw8M** [comment] 2024-04-18 12:22
I can confirm this issue.

I also thank for Treeline and Treetag. Unique and powerful programs.

**Comment by doug-101** [comment] 2024-05-16 00:32
A work-around fix has been pushed to GitHub and will be in the next release.  This had quit working due to changes in how Android handles permissions.

**Comment by doug-101** [comment] 2024-07-25 00:36
This fix was included in the 0.7.3 release (just completed).

**Comment by supertoothy** [comment] 2024-08-12 11:42
> This fix was included in the 0.7.3 release (just completed).

Thank you!

**Closed as completed** 2024-11-24 19:04 UTC
